AllCops:
  NewCops: enable
  DisplayCopNames: true #Muestra la regla que falla

  Exclude: #Configurado para que solo analice las entidades.
    - 'bin/**'  #Ignora los archivos de la carpeta bin
    - 'config/**'  #Ignora los archivos de la carpeta config
    - 'docs/**'  #Ignora los archivos de la carpeta docs
    - 'configu_ssh/**' #Ignora los archivos de configuración de SSH
    - 'spec-test/**'  #Ignora los archivos de test
    - 'Rakefile' #Ignora el archivo Rakefile
    - 'Gemfile'  #Ignora el archivo Gemfile
