FROM ruby:alpine

RUN apk add --no-cache build-base

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle config --global frozen 1
RUN bundle install

WORKDIR /app/test

ENTRYPOINT ["bundle", "exec", "rake", "test"]