FROM rubylang/ruby:latest

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle config --global frozen 1
RUN bundle install

WORKDIR /app/test

ENTRYPOINT ["bundle", "exec", "rake", "test"]